import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavigationMenuDemo } from "@/components/Navbar";
import { Providers } from "@/components/ThemeProvider";
import ThemeToggle from "@/components/ThemeToggle";
import Link from "next/link";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { Toaster } from "sonner";
import Logout from "@/components/Logout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {

  const session = await getServerSession(authOptions);

  return (
    <html lang="en" suppressHydrationWarning>
      <body className="text-black dark:text-white bg-white dark:bg-black">
        <Providers>
          <div className="flex justify-between px-6 py-2 sticky top-0 z-50 backdrop-blur-md bg-white/40 dark:bg-black/40 border-b dark:border-gray-700">
            <div className="flex gap-10">
              <Link href="/"><div className="text-3xl font-extrabold">CodeTrail{"</>"}</div></Link>
              <NavigationMenuDemo />
            </div>

            <div className="flex justify-center gap-1 items-center">
              {session===null ? 
                <div className="flex justify-center gap-1 items-center">
                  <Link href="/auth/signin" className="px-4 py-1 rounded-md border bg-white hover:bg-black hover:text-white dark:bg-black dark:hover:bg-white dark:hover:text-black">
                    Login
                  </Link>
                  <p className="text-xl">/</p>
                  <Link href="/auth/signup" className="px-4 py-1 rounded-md border bg-white hover:bg-black hover:text-white dark:bg-black dark:hover:bg-white dark:hover:text-black">
                    Signup
                  </Link>
                </div>
                :
                <div className="flex justify-center gap-1 items-center">
                  {/* <Link href="/profile" className="px-3 py-1 rounded-md border bg-white hover:bg-black hover:text-white dark:bg-black dark:hover:bg-white dark:hover:text-black flex items-center gap-1.5">
                    <UserCircle size={16} />
                    Profile
                  </Link>
                  <p className="text-xl">/</p> */}
                  <Logout/>
                </div>         
              }
              <ThemeToggle />
            </div>
          </div>
          <Toaster richColors position="bottom-right" />
          {children}
        </Providers>
      </body>
    </html>
  );
}
